name: First Workflow
on: [push]

jobs:
  phpcs:
      name: WPCS
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          composer install
      - name: Run PHPCS
        run: |
          composer require "squizlabs/php_codesniffer=*"
          composer require "wp-coding-standards/wpcs" --working-dir=vendor/wp-coding-standards
          composer require --dev phpcompatibility/phpcompatibility-wp --working-dir=vendor/phpcompatibility-wp
          