name: First Workflow
on: [push]

jobs:
  phpcs:
      name: WPCS
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          composer install
      - name: Run PHPCS
        run: |
          php vendor/bin/phpcs .
          